### ISSUE TITLE
[Threads] Public threads are treated as private when using `.invite`

### ISSUE THREAD

**Issue by TechnoDrive** [dev-launchers-sandbox/project__discord-bot#109]
### Expected Behavior
Any person in a thread should be able to invite (an)other user(s) to said thread.

### Current Behavior
When any person other than the owner of the thread invites someone to a thread via `.invite <thread-channel>`, the thread is reported as "private" even if the thread is public.

### Steps to Reproduce
1. Create a new thread: `.create bug-testing-thread`
     - Threads are public by default now, so keep this in mind.
     - Because they are public by default, they will appear in #thread-directory
2. Ask someone else to join your thread via #thread-directory
     - This is important because the owner bypasses the restriction.
3. Ask that person to use `.invite <#bug testing thread ID>`
4. The bot will reject the user's command with "The thread is private, only the owner can do this."

**Comment by guillermosanta** [comment]
Thanks for reporting it. The issue has now been fixed.
